DEFAULT_PERMISSION_DEFINITIONS = [
    {
        "code": "auth.me",
        "resource": "auth",
        "action": "me",
        "description": "Read the currently authenticated user profile.",
    },
    {
        "code": "users.read",
        "resource": "users",
        "action": "read",
        "description": "View user records and assignments.",
    },
    {
        "code": "users.write",
        "resource": "users",
        "action": "write",
        "description": "Create and update user records.",
    },
    {
        "code": "roles.read",
        "resource": "roles",
        "action": "read",
        "description": "View roles and permissions.",
    },
    {
        "code": "roles.write",
        "resource": "roles",
        "action": "write",
        "description": "Manage roles and role assignments.",
    },
    {
        "code": "device_catalog.read",
        "resource": "device_catalog",
        "action": "read",
        "description": "View manufacturers, models, firmware, communication profiles, and meter profiles.",
    },
    {
        "code": "device_catalog.write",
        "resource": "device_catalog",
        "action": "write",
        "description": "Manage manufacturers, models, firmware, communication profiles, and meter profiles.",
    },
    {
        "code": "meters.read",
        "resource": "meters",
        "action": "read",
        "description": "View meter registry records.",
    },
    {
        "code": "meters.write",
        "resource": "meters",
        "action": "write",
        "description": "Create and update meter registry records.",
    },
    {
        "code": "meters.status.write",
        "resource": "meters",
        "action": "status_write",
        "description": "Change meter lifecycle status.",
    },
    {
        "code": "connectivity.read",
        "resource": "connectivity",
        "action": "read",
        "description": "View connectivity endpoints and protocol association profiles.",
    },
    {
        "code": "connectivity.write",
        "resource": "connectivity",
        "action": "write",
        "description": "Create and update connectivity endpoints and protocol association profiles.",
    },
    {
        "code": "connectivity.assign.write",
        "resource": "connectivity",
        "action": "assign_write",
        "description": "Assign communication endpoints to meters.",
    },
    {
        "code": "connectivity.sessions.read",
        "resource": "connectivity",
        "action": "sessions_read",
        "description": "View connectivity session history.",
    },
    {
        "code": "connectivity.credentials.read",
        "resource": "connectivity_credentials",
        "action": "read",
        "description": "View connectivity credential placeholders.",
    },
    {
        "code": "connectivity.credentials.write",
        "resource": "connectivity_credentials",
        "action": "write",
        "description": "Create and update connectivity credential placeholders.",
    },
    {
        "code": "commands.read",
        "resource": "commands",
        "action": "read",
        "description": "View command requests and execution history.",
    },
    {
        "code": "commands.write",
        "resource": "commands",
        "action": "write",
        "description": "Manage durable command records.",
    },
    {
        "code": "commands.execute.request",
        "resource": "commands",
        "action": "execute_request",
        "description": "Request new command executions for a target meter.",
    },
    {
        "code": "commands.templates.read",
        "resource": "command_templates",
        "action": "read",
        "description": "View command templates.",
    },
    {
        "code": "commands.templates.write",
        "resource": "command_templates",
        "action": "write",
        "description": "Create and update command templates.",
    },
    {
        "code": "commands.cancel",
        "resource": "commands",
        "action": "cancel",
        "description": "Cancel safely cancellable commands.",
    },
    {
        "code": "jobs.read",
        "resource": "jobs",
        "action": "read",
        "description": "View job definitions.",
    },
    {
        "code": "jobs.write",
        "resource": "jobs",
        "action": "write",
        "description": "Create and update job definitions and manual runs.",
    },
    {
        "code": "jobs.runs.read",
        "resource": "job_runs",
        "action": "read",
        "description": "View job run history.",
    },
    {
        "code": "jobs.targets.read",
        "resource": "job_definition_targets",
        "action": "read",
        "description": "View job definition target assignments.",
    },
    {
        "code": "jobs.targets.write",
        "resource": "job_definition_targets",
        "action": "write",
        "description": "Manage job definition target assignments.",
    },
    {
        "code": "jobs.generate.internal",
        "resource": "scheduler",
        "action": "generate_internal",
        "description": "Internal scheduler run generation capability.",
    },
    {
        "code": "readings.read",
        "resource": "readings",
        "action": "read",
        "description": "View ingested meter readings and snapshots.",
    },
    {
        "code": "readings.write",
        "resource": "readings",
        "action": "write",
        "description": "Internal ingestion of meter readings.",
    },
    {
        "code": "profiles.read",
        "resource": "load_profiles",
        "action": "read",
        "description": "View load profile channels and intervals.",
    },
    {
        "code": "profiles.write",
        "resource": "load_profiles",
        "action": "write",
        "description": "Manage load profile channels.",
    },
    {
        "code": "events.read",
        "resource": "events",
        "action": "read",
        "description": "View ingested meter events.",
    },
    {
        "code": "consumers.read",
        "resource": "consumers",
        "action": "read",
        "description": "View subscriber and consumer account visibility surfaces.",
    },
]

DEFAULT_ROLE_DEFINITIONS = [
    {
        "code": "super_admin",
        "name": "Super Admin",
        "description": "Full platform administration access.",
        "is_system": True,
        "permission_codes": [permission["code"] for permission in DEFAULT_PERMISSION_DEFINITIONS],
    },
    {
        "code": "platform_admin",
        "name": "Platform Admin",
        "description": "Administrative access to users and role management.",
        "is_system": True,
        "permission_codes": [
            "auth.me",
            "users.read",
            "users.write",
            "roles.read",
            "roles.write",
            "device_catalog.read",
            "device_catalog.write",
            "meters.read",
            "meters.write",
            "meters.status.write",
            "connectivity.read",
            "connectivity.write",
            "connectivity.assign.write",
            "connectivity.sessions.read",
            "connectivity.credentials.read",
            "connectivity.credentials.write",
            "commands.read",
            "commands.write",
            "commands.execute.request",
            "commands.templates.read",
            "commands.templates.write",
            "commands.cancel",
            "jobs.read",
            "jobs.write",
            "jobs.runs.read",
            "jobs.targets.read",
            "jobs.targets.write",
            "readings.read",
            "readings.write",
            "profiles.read",
            "profiles.write",
            "events.read",
            "consumers.read",
        ],
    },
    {
        "code": "platform_viewer",
        "name": "Platform Viewer",
        "description": "Read-only access to administration views.",
        "is_system": True,
        "permission_codes": [
            "auth.me",
            "users.read",
            "roles.read",
            "device_catalog.read",
            "meters.read",
            "connectivity.read",
            "connectivity.sessions.read",
            "connectivity.credentials.read",
            "commands.read",
            "commands.templates.read",
            "jobs.read",
            "jobs.runs.read",
            "jobs.targets.read",
            "readings.read",
            "profiles.read",
            "events.read",
            "consumers.read",
        ],
    },
]
