"""add readings and event ingestion foundation"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '1ac97674d941'
down_revision = '6312df66e84b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_profile_channels',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('channel_code', sa.String(length=64), nullable=False),
    sa.Column('obis_code', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_load_profile_channels_meter_id_meters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_profile_channels')),
    sa.UniqueConstraint('meter_id', 'channel_code', name=op.f('uq_load_profile_channels_meter_id'))
    )
    op.create_index('ix_load_profile_channels_meter_active', 'load_profile_channels', ['meter_id', 'is_active'], unique=False)
    op.create_table('meter_reading_batches',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('related_command_id', sa.Uuid(), nullable=True),
    sa.Column('related_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('session_history_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('manual_read', 'scheduled_read', 'command_result', 'import', 'runtime_poll', name='reading_source_type'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', name='reading_batch_status'), server_default='received', nullable=False),
    sa.Column('reading_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_reading_batches_meter_id_meters')),
    sa.ForeignKeyConstraint(['related_attempt_id'], ['command_execution_attempts.id'], name=op.f('fk_meter_reading_batches_related_attempt_id_command_execution_attempts')),
    sa.ForeignKeyConstraint(['related_command_id'], ['commands.id'], name=op.f('fk_meter_reading_batches_related_command_id_commands')),
    sa.ForeignKeyConstraint(['session_history_id'], ['connectivity_session_history.id'], name=op.f('fk_meter_reading_batches_session_history_id_connectivity_session_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_reading_batches'))
    )
    op.create_index('ix_meter_reading_batches_attempt_id', 'meter_reading_batches', ['related_attempt_id'], unique=False)
    op.create_index('ix_meter_reading_batches_correlation_id', 'meter_reading_batches', ['correlation_id'], unique=False)
    op.create_index('ix_meter_reading_batches_meter_captured_at', 'meter_reading_batches', ['meter_id', 'captured_at'], unique=False)
    op.create_index('ix_meter_reading_batches_session_history_id', 'meter_reading_batches', ['session_history_id'], unique=False)
    op.create_table('load_profile_intervals',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quality', sa.Enum('good', 'estimated', 'suspect', 'missing', name='reading_quality'), nullable=True),
    sa.Column('source_batch_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['load_profile_channels.id'], name=op.f('fk_load_profile_intervals_channel_id_load_profile_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_load_profile_intervals_meter_id_meters')),
    sa.ForeignKeyConstraint(['source_batch_id'], ['meter_reading_batches.id'], name=op.f('fk_load_profile_intervals_source_batch_id_meter_reading_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_profile_intervals')),
    sa.UniqueConstraint('channel_id', 'interval_start', 'interval_end', name=op.f('uq_load_profile_intervals_channel_id'))
    )
    op.create_index('ix_load_profile_intervals_meter_interval_start', 'load_profile_intervals', ['meter_id', 'interval_start'], unique=False)
    op.create_index('ix_load_profile_intervals_source_batch_id', 'load_profile_intervals', ['source_batch_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('obis_code', sa.String(length=64), nullable=False),
    sa.Column('reading_type', sa.Enum('scalar', 'register', 'instantaneous', 'demand', name='reading_type'), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('quality', sa.Enum('good', 'estimated', 'suspect', 'missing', name='reading_quality'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['meter_reading_batches.id'], name=op.f('fk_meter_readings_batch_id_meter_reading_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_readings_meter_id_meters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_readings'))
    )
    op.create_index('ix_meter_readings_batch_id', 'meter_readings', ['batch_id'], unique=False)
    op.create_index('ix_meter_readings_meter_captured_at', 'meter_readings', ['meter_id', 'captured_at'], unique=False)
    op.create_index('ix_meter_readings_obis_code', 'meter_readings', ['obis_code'], unique=False)
    op.create_table('meter_register_snapshots',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('related_batch_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('billing', 'instantaneous', 'nameplate', 'clock', 'diagnostics', name='snapshot_type'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_register_snapshots_meter_id_meters')),
    sa.ForeignKeyConstraint(['related_batch_id'], ['meter_reading_batches.id'], name=op.f('fk_meter_register_snapshots_related_batch_id_meter_reading_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_register_snapshots'))
    )
    op.create_index('ix_meter_register_snapshots_batch_id', 'meter_register_snapshots', ['related_batch_id'], unique=False)
    op.create_index('ix_meter_register_snapshots_meter_captured_at', 'meter_register_snapshots', ['meter_id', 'captured_at'], unique=False)
    op.create_index('ix_meter_register_snapshots_snapshot_type', 'meter_register_snapshots', ['snapshot_type'], unique=False)
    op.add_column('meter_events', sa.Column('related_batch_id', sa.Uuid(), nullable=True))
    op.add_column('meter_events', sa.Column('related_attempt_id', sa.Uuid(), nullable=True))
    op.add_column('meter_events', sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('meter_events', sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('meter_events', sa.Column('correlation_id', sa.String(length=128), nullable=True))
    op.alter_column('meter_events', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_meter_events_correlation_id', 'meter_events', ['correlation_id'], unique=False)
    op.create_foreign_key(op.f('fk_meter_events_related_attempt_id_command_execution_attempts'), 'meter_events', 'command_execution_attempts', ['related_attempt_id'], ['id'])
    op.create_foreign_key(op.f('fk_meter_events_related_batch_id_meter_reading_batches'), 'meter_events', 'meter_reading_batches', ['related_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_meter_events_related_batch_id_meter_reading_batches'), 'meter_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_meter_events_related_attempt_id_command_execution_attempts'), 'meter_events', type_='foreignkey')
    op.drop_index('ix_meter_events_correlation_id', table_name='meter_events')
    op.alter_column('meter_events', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('meter_events', 'correlation_id')
    op.drop_column('meter_events', 'normalized_payload')
    op.drop_column('meter_events', 'received_at')
    op.drop_column('meter_events', 'related_attempt_id')
    op.drop_column('meter_events', 'related_batch_id')
    op.drop_index('ix_meter_register_snapshots_snapshot_type', table_name='meter_register_snapshots')
    op.drop_index('ix_meter_register_snapshots_meter_captured_at', table_name='meter_register_snapshots')
    op.drop_index('ix_meter_register_snapshots_batch_id', table_name='meter_register_snapshots')
    op.drop_table('meter_register_snapshots')
    op.drop_index('ix_meter_readings_obis_code', table_name='meter_readings')
    op.drop_index('ix_meter_readings_meter_captured_at', table_name='meter_readings')
    op.drop_index('ix_meter_readings_batch_id', table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index('ix_load_profile_intervals_source_batch_id', table_name='load_profile_intervals')
    op.drop_index('ix_load_profile_intervals_meter_interval_start', table_name='load_profile_intervals')
    op.drop_table('load_profile_intervals')
    op.drop_index('ix_meter_reading_batches_session_history_id', table_name='meter_reading_batches')
    op.drop_index('ix_meter_reading_batches_meter_captured_at', table_name='meter_reading_batches')
    op.drop_index('ix_meter_reading_batches_correlation_id', table_name='meter_reading_batches')
    op.drop_index('ix_meter_reading_batches_attempt_id', table_name='meter_reading_batches')
    op.drop_table('meter_reading_batches')
    op.drop_index('ix_load_profile_channels_meter_active', table_name='load_profile_channels')
    op.drop_table('load_profile_channels')
    # ### end Alembic commands ###
