"""create initial platform domain schema"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '46c4d7ab94b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('communication_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_communication_profiles_code'))
    )
    op.create_table('consumers',
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('consumer_type', sa.String(length=64), server_default='residential', nullable=False),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumers')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_consumers_external_ref')),
    sa.UniqueConstraint('national_id', name=op.f('uq_consumers_national_id'))
    )
    op.create_table('meter_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_manufacturers')),
    sa.UniqueConstraint('code', name=op.f('uq_meter_manufacturers_code')),
    sa.UniqueConstraint('name', name=op.f('uq_meter_manufacturers_name'))
    )
    op.create_table('meter_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol_family', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_meter_profiles_code'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code')),
    sa.UniqueConstraint('resource', 'action', name=op.f('uq_permissions_resource'))
    )
    op.create_table('regions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'inactive', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_regions_code')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'locked', 'suspended', name='user_status'), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_entity_lookup', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_key', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'running', 'succeeded', 'failed', 'paused', name='job_status'), server_default='draft', nullable=False),
    sa.Column('schedule_expression', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_jobs_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('job_key', name=op.f('uq_jobs_job_key'))
    )
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('meter_models',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phase_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['meter_manufacturers.id'], name=op.f('fk_meter_models_manufacturer_id_meter_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_models')),
    sa.UniqueConstraint('manufacturer_id', 'model_code', name=op.f('uq_meter_models_manufacturer_id'))
    )
    op.create_index('ix_meter_models_manufacturer_id', 'meter_models', ['manufacturer_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_role_permissions_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions_role_id'))
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('sectors',
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'inactive', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_sectors_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('region_id', 'code', name=op.f('uq_sectors_region_id'))
    )
    op.create_index('ix_sectors_region_id', 'sectors', ['region_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=64), server_default='platform', nullable=False),
    sa.Column('scope_identifier', sa.String(length=128), server_default='global', nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_user_role_assignments_assigned_by_user_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_assignments_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role_assignments')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_identifier', name=op.f('uq_user_role_assignments_user_id'))
    )
    op.create_index('ix_user_role_assignments_role_id', 'user_role_assignments', ['role_id'], unique=False)
    op.create_index('ix_user_role_assignments_scope', 'user_role_assignments', ['scope_type', 'scope_identifier'], unique=False)
    op.create_table('job_runs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'running', 'succeeded', 'failed', 'paused', name='job_status'), server_default='ready', nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_job_runs_correlation_id'))
    )
    op.create_index('ix_job_runs_job_queued_at', 'job_runs', ['job_id', 'queued_at'], unique=False)
    op.create_index('ix_job_runs_job_status', 'job_runs', ['job_id', 'status'], unique=False)
    op.create_table('meter_firmware_versions',
    sa.Column('meter_model_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_model_id'], ['meter_models.id'], name=op.f('fk_meter_firmware_versions_meter_model_id_meter_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_firmware_versions')),
    sa.UniqueConstraint('meter_model_id', 'version', name=op.f('uq_meter_firmware_versions_meter_model_id'))
    )
    op.create_index('ix_meter_firmware_versions_meter_model_id', 'meter_firmware_versions', ['meter_model_id'], unique=False)
    op.create_table('substations',
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'inactive', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_substations_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substations')),
    sa.UniqueConstraint('sector_id', 'code', name=op.f('uq_substations_sector_id'))
    )
    op.create_index('ix_substations_sector_id', 'substations', ['sector_id'], unique=False)
    op.create_table('feeders',
    sa.Column('substation_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'inactive', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], name=op.f('fk_feeders_substation_id_substations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeders')),
    sa.UniqueConstraint('substation_id', 'code', name=op.f('uq_feeders_substation_id'))
    )
    op.create_index('ix_feeders_substation_id', 'feeders', ['substation_id'], unique=False)
    op.create_table('transformers',
    sa.Column('feeder_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'inactive', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], name=op.f('fk_transformers_feeder_id_feeders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transformers')),
    sa.UniqueConstraint('feeder_id', 'code', name=op.f('uq_transformers_feeder_id'))
    )
    op.create_index('ix_transformers_feeder_id', 'transformers', ['feeder_id'], unique=False)
    op.create_table('service_points',
    sa.Column('service_point_code', sa.String(length=128), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('transformer_id', sa.Uuid(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('premises_type', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_service_points_sector_id_sectors')),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], name=op.f('fk_service_points_transformer_id_transformers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_points')),
    sa.UniqueConstraint('service_point_code', name=op.f('uq_service_points_service_point_code'))
    )
    op.create_index('ix_service_points_sector_id', 'service_points', ['sector_id'], unique=False)
    op.create_index('ix_service_points_transformer_id', 'service_points', ['transformer_id'], unique=False)
    op.create_table('accounts',
    sa.Column('consumer_id', sa.Uuid(), nullable=False),
    sa.Column('service_point_id', sa.Uuid(), nullable=True),
    sa.Column('account_number', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), server_default='active', nullable=False),
    sa.Column('billing_cycle', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], name=op.f('fk_accounts_consumer_id_consumers')),
    sa.ForeignKeyConstraint(['service_point_id'], ['service_points.id'], name=op.f('fk_accounts_service_point_id_service_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('account_number', name=op.f('uq_accounts_account_number'))
    )
    op.create_index('ix_accounts_consumer_id', 'accounts', ['consumer_id'], unique=False)
    op.create_index('ix_accounts_service_point_id', 'accounts', ['service_point_id'], unique=False)
    op.create_table('meters',
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('utility_meter_id', sa.String(length=128), nullable=True),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('meter_model_id', sa.Uuid(), nullable=False),
    sa.Column('meter_profile_id', sa.Uuid(), nullable=True),
    sa.Column('firmware_version_id', sa.Uuid(), nullable=True),
    sa.Column('communication_profile_id', sa.Uuid(), nullable=True),
    sa.Column('transformer_id', sa.Uuid(), nullable=True),
    sa.Column('service_point_id', sa.Uuid(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('registered', 'commissioned', 'active', 'inactive', 'retired', name='meter_lifecycle_status'), server_default='registered', nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_profile_id'], ['communication_profiles.id'], name=op.f('fk_meters_communication_profile_id_communication_profiles')),
    sa.ForeignKeyConstraint(['firmware_version_id'], ['meter_firmware_versions.id'], name=op.f('fk_meters_firmware_version_id_meter_firmware_versions')),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['meter_manufacturers.id'], name=op.f('fk_meters_manufacturer_id_meter_manufacturers')),
    sa.ForeignKeyConstraint(['meter_model_id'], ['meter_models.id'], name=op.f('fk_meters_meter_model_id_meter_models')),
    sa.ForeignKeyConstraint(['meter_profile_id'], ['meter_profiles.id'], name=op.f('fk_meters_meter_profile_id_meter_profiles')),
    sa.ForeignKeyConstraint(['service_point_id'], ['service_points.id'], name=op.f('fk_meters_service_point_id_service_points')),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], name=op.f('fk_meters_transformer_id_transformers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meters')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_meters_serial_number')),
    sa.UniqueConstraint('utility_meter_id', name=op.f('uq_meters_utility_meter_id'))
    )
    op.create_index('ix_meters_lifecycle_status', 'meters', ['lifecycle_status'], unique=False)
    op.create_index('ix_meters_model_id', 'meters', ['meter_model_id'], unique=False)
    op.create_index('ix_meters_service_point_id', 'meters', ['service_point_id'], unique=False)
    op.create_index('ix_meters_transformer_id', 'meters', ['transformer_id'], unique=False)
    op.create_table('commands',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('job_run_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('command_type', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'in_progress', 'succeeded', 'failed', 'cancelled', name='command_status'), server_default='pending', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], name=op.f('fk_commands_job_run_id_job_runs')),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_commands_meter_id_meters')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_commands_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_commands_correlation_id'))
    )
    op.create_index('ix_commands_job_run_id', 'commands', ['job_run_id'], unique=False)
    op.create_index('ix_commands_meter_requested_at', 'commands', ['meter_id', 'requested_at'], unique=False)
    op.create_index('ix_commands_status_requested_at', 'commands', ['status', 'requested_at'], unique=False)
    op.create_table('meter_account_assignments',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('service_point_id', sa.Uuid(), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_meter_account_assignments_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_account_assignments_meter_id_meters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_point_id'], ['service_points.id'], name=op.f('fk_meter_account_assignments_service_point_id_service_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_account_assignments')),
    sa.UniqueConstraint('meter_id', 'account_id', 'active_from', name=op.f('uq_meter_account_assignments_meter_id'))
    )
    op.create_index('ix_meter_account_assignments_account_id', 'meter_account_assignments', ['account_id'], unique=False)
    op.create_index('ix_meter_account_assignments_meter_current', 'meter_account_assignments', ['meter_id', 'is_current'], unique=False)
    op.create_table('meter_connectivity_history',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', 'unknown', name='connectivity_status'), nullable=False),
    sa.Column('session_reference', sa.String(length=128), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_connectivity_history_meter_id_meters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_connectivity_history'))
    )
    op.create_index('ix_meter_connectivity_history_meter_recorded_at', 'meter_connectivity_history', ['meter_id', 'recorded_at'], unique=False)
    op.create_index('ix_meter_connectivity_history_meter_status', 'meter_connectivity_history', ['meter_id', 'status'], unique=False)
    op.create_table('meter_status_history',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'commissioned', 'active', 'inactive', 'retired', name='meter_lifecycle_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_meter_status_history_changed_by_user_id_users')),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_status_history_meter_id_meters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_status_history'))
    )
    op.create_index('ix_meter_status_history_meter_recorded_at', 'meter_status_history', ['meter_id', 'recorded_at'], unique=False)
    op.create_index('ix_meter_status_history_meter_status', 'meter_status_history', ['meter_id', 'status'], unique=False)
    op.create_table('meter_events',
    sa.Column('meter_id', sa.Uuid(), nullable=True),
    sa.Column('related_command_id', sa.Uuid(), nullable=True),
    sa.Column('event_code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='event_severity'), server_default='info', nullable=False),
    sa.Column('state', sa.Enum('open', 'acknowledged', 'resolved', name='event_state'), server_default='open', nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_events_meter_id_meters')),
    sa.ForeignKeyConstraint(['related_command_id'], ['commands.id'], name=op.f('fk_meter_events_related_command_id_commands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_events'))
    )
    op.create_index('ix_meter_events_event_code', 'meter_events', ['event_code'], unique=False)
    op.create_index('ix_meter_events_meter_occurred_at', 'meter_events', ['meter_id', 'occurred_at'], unique=False)
    op.create_index('ix_meter_events_state_severity', 'meter_events', ['state', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meter_events_state_severity', table_name='meter_events')
    op.drop_index('ix_meter_events_meter_occurred_at', table_name='meter_events')
    op.drop_index('ix_meter_events_event_code', table_name='meter_events')
    op.drop_table('meter_events')
    op.drop_index('ix_meter_status_history_meter_status', table_name='meter_status_history')
    op.drop_index('ix_meter_status_history_meter_recorded_at', table_name='meter_status_history')
    op.drop_table('meter_status_history')
    op.drop_index('ix_meter_connectivity_history_meter_status', table_name='meter_connectivity_history')
    op.drop_index('ix_meter_connectivity_history_meter_recorded_at', table_name='meter_connectivity_history')
    op.drop_table('meter_connectivity_history')
    op.drop_index('ix_meter_account_assignments_meter_current', table_name='meter_account_assignments')
    op.drop_index('ix_meter_account_assignments_account_id', table_name='meter_account_assignments')
    op.drop_table('meter_account_assignments')
    op.drop_index('ix_commands_status_requested_at', table_name='commands')
    op.drop_index('ix_commands_meter_requested_at', table_name='commands')
    op.drop_index('ix_commands_job_run_id', table_name='commands')
    op.drop_table('commands')
    op.drop_index('ix_meters_transformer_id', table_name='meters')
    op.drop_index('ix_meters_service_point_id', table_name='meters')
    op.drop_index('ix_meters_model_id', table_name='meters')
    op.drop_index('ix_meters_lifecycle_status', table_name='meters')
    op.drop_table('meters')
    op.drop_index('ix_accounts_service_point_id', table_name='accounts')
    op.drop_index('ix_accounts_consumer_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_service_points_transformer_id', table_name='service_points')
    op.drop_index('ix_service_points_sector_id', table_name='service_points')
    op.drop_table('service_points')
    op.drop_index('ix_transformers_feeder_id', table_name='transformers')
    op.drop_table('transformers')
    op.drop_index('ix_feeders_substation_id', table_name='feeders')
    op.drop_table('feeders')
    op.drop_index('ix_substations_sector_id', table_name='substations')
    op.drop_table('substations')
    op.drop_index('ix_meter_firmware_versions_meter_model_id', table_name='meter_firmware_versions')
    op.drop_table('meter_firmware_versions')
    op.drop_index('ix_job_runs_job_status', table_name='job_runs')
    op.drop_index('ix_job_runs_job_queued_at', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_user_role_assignments_scope', table_name='user_role_assignments')
    op.drop_index('ix_user_role_assignments_role_id', table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index('ix_sectors_region_id', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_meter_models_manufacturer_id', table_name='meter_models')
    op.drop_table('meter_models')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_audit_logs_entity_lookup', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('permissions')
    op.drop_table('meter_profiles')
    op.drop_table('meter_manufacturers')
    op.drop_table('consumers')
    op.drop_table('communication_profiles')
    # ### end Alembic commands ###
