"""add scheduler run generation foundation"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '6312df66e84b'
down_revision = '5d4072b190e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_definition_target_assignments',
    sa.Column('job_definition_id', sa.Uuid(), nullable=False),
    sa.Column('target_meter_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_definition_id'], ['jobs.id'], name=op.f('fk_job_definition_target_assignments_job_definition_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_meter_id'], ['meters.id'], name=op.f('fk_job_definition_target_assignments_target_meter_id_meters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_definition_target_assignments')),
    sa.UniqueConstraint('job_definition_id', 'target_meter_id', name=op.f('uq_job_definition_target_assignments_job_definition_id'))
    )
    op.create_index('ix_job_definition_target_assignments_job_active', 'job_definition_target_assignments', ['job_definition_id', 'is_active'], unique=False)
    op.create_index('ix_job_definition_target_assignments_meter_active', 'job_definition_target_assignments', ['target_meter_id', 'is_active'], unique=False)
    op.create_index('uq_job_runs_job_meter_scheduled_for', 'job_runs', ['job_id', 'target_meter_id', 'scheduled_for'], unique=True, postgresql_where=sa.text('target_meter_id IS NOT NULL'))
    op.create_index('uq_job_runs_job_system_scheduled_for', 'job_runs', ['job_id', 'scheduled_for'], unique=True, postgresql_where=sa.text('target_meter_id IS NULL AND target_endpoint_id IS NULL'))
    op.add_column('jobs', sa.Column('run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'run_at')
    op.drop_index('uq_job_runs_job_system_scheduled_for', table_name='job_runs', postgresql_where=sa.text('target_meter_id IS NULL AND target_endpoint_id IS NULL'))
    op.drop_index('uq_job_runs_job_meter_scheduled_for', table_name='job_runs', postgresql_where=sa.text('target_meter_id IS NOT NULL'))
    op.drop_index('ix_job_definition_target_assignments_meter_active', table_name='job_definition_target_assignments')
    op.drop_index('ix_job_definition_target_assignments_job_active', table_name='job_definition_target_assignments')
    op.drop_table('job_definition_target_assignments')
    # ### end Alembic commands ###
