"""create connectivity foundation"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = 'f7d20a7d2bb2'
down_revision = 'de970c68a2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_endpoints',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_type', sa.Enum('tcp', 'serial', 'modem', 'gateway', 'virtual', name='communication_endpoint_type'), nullable=False),
    sa.Column('transport_type', sa.Enum('tcp_ip', 'serial', 'modem', 'gateway', 'virtual', name='connectivity_transport_type'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('serial_port_name', sa.String(length=255), nullable=True),
    sa.Column('baud_rate', sa.Integer(), nullable=True),
    sa.Column('parity', sa.Enum('none', 'even', 'odd', name='serial_parity'), nullable=True),
    sa.Column('data_bits', sa.Integer(), nullable=True),
    sa.Column('stop_bits', sa.Enum('one', 'one_point_five', 'two', name='serial_stop_bits'), nullable=True),
    sa.Column('sim_iccid', sa.String(length=64), nullable=True),
    sa.Column('sim_msisdn', sa.String(length=64), nullable=True),
    sa.Column('imei', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('apn', sa.String(length=255), nullable=True),
    sa.Column('network_provider', sa.String(length=128), nullable=True),
    sa.Column('gateway_identifier', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_endpoints')),
    sa.UniqueConstraint('code', name=op.f('uq_communication_endpoints_code'))
    )
    op.create_index('ix_communication_endpoints_endpoint_type', 'communication_endpoints', ['endpoint_type'], unique=False)
    op.create_index('ix_communication_endpoints_is_active', 'communication_endpoints', ['is_active'], unique=False)
    op.create_index('ix_communication_endpoints_transport_type', 'communication_endpoints', ['transport_type'], unique=False)
    op.create_table('connectivity_credentials',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('credential_type', sa.Enum('password', 'apn', 'token', 'key_ref', name='credential_type'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectivity_credentials')),
    sa.UniqueConstraint('code', name=op.f('uq_connectivity_credentials_code'))
    )
    op.create_index('ix_connectivity_credentials_is_active', 'connectivity_credentials', ['is_active'], unique=False)
    op.create_table('protocol_association_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol_family', sa.Enum('dlms_cosem', name='protocol_family'), server_default='dlms_cosem', nullable=False),
    sa.Column('iec62056_21_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('iec_device_address', sa.String(length=128), nullable=True),
    sa.Column('iec_baud_rate', sa.Integer(), nullable=True),
    sa.Column('client_address', sa.Integer(), nullable=False),
    sa.Column('server_address', sa.Integer(), nullable=False),
    sa.Column('authentication_mode', sa.Enum('none', 'low', 'high', 'high_gmac', name='association_authentication_mode'), server_default='none', nullable=False),
    sa.Column('password_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('security_suite', sa.String(length=64), nullable=True),
    sa.Column('system_title', sa.String(length=64), nullable=True),
    sa.Column('auth_key_ref', sa.String(length=255), nullable=True),
    sa.Column('block_cipher_key_ref', sa.String(length=255), nullable=True),
    sa.Column('dedicated_key_ref', sa.String(length=255), nullable=True),
    sa.Column('invocation_counter_obis', sa.String(length=64), nullable=True),
    sa.Column('meter_time_obis', sa.String(length=64), nullable=True),
    sa.Column('profile_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocol_association_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_protocol_association_profiles_code'))
    )
    op.create_index('ix_protocol_association_profiles_is_active', 'protocol_association_profiles', ['is_active'], unique=False)
    op.create_index('ix_protocol_association_profiles_protocol_family', 'protocol_association_profiles', ['protocol_family'], unique=False)
    op.create_table('connectivity_session_history',
    sa.Column('meter_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint_id', sa.Uuid(), nullable=True),
    sa.Column('protocol_association_profile_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'timed_out', 'cancelled', name='connectivity_session_status'), nullable=False),
    sa.Column('session_purpose', sa.Enum('connectivity_test', 'device_onboarding', 'profile_validation', 'manual_diagnostic', name='connectivity_session_purpose'), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('transport_latency_ms', sa.Integer(), nullable=True),
    sa.Column('handshake_stage', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['communication_endpoints.id'], name=op.f('fk_connectivity_session_history_endpoint_id_communication_endpoints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_connectivity_session_history_meter_id_meters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_association_profile_id'], ['protocol_association_profiles.id'], name=op.f('fk_connectivity_session_history_protocol_association_profile_id_protocol_association_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectivity_session_history'))
    )
    op.create_index('ix_connectivity_session_history_correlation_id', 'connectivity_session_history', ['correlation_id'], unique=False)
    op.create_index('ix_connectivity_session_history_endpoint_started_at', 'connectivity_session_history', ['endpoint_id', 'started_at'], unique=False)
    op.create_index('ix_connectivity_session_history_meter_started_at', 'connectivity_session_history', ['meter_id', 'started_at'], unique=False)
    op.create_index('ix_connectivity_session_history_recent_started_at', 'connectivity_session_history', ['started_at'], unique=False)
    op.create_index('ix_connectivity_session_history_status_started_at', 'connectivity_session_history', ['status', 'started_at'], unique=False)
    op.create_table('meter_endpoint_assignments',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assignment_status', sa.Enum('active', 'inactive', 'suspended', name='endpoint_assignment_status'), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['communication_endpoints.id'], name=op.f('fk_meter_endpoint_assignments_endpoint_id_communication_endpoints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_endpoint_assignments_meter_id_meters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_endpoint_assignments'))
    )
    op.create_index('ix_meter_endpoint_assignments_endpoint_active', 'meter_endpoint_assignments', ['endpoint_id', 'assignment_status'], unique=False)
    op.create_index('ix_meter_endpoint_assignments_meter_active', 'meter_endpoint_assignments', ['meter_id', 'assignment_status', 'assigned_at'], unique=False)
    op.create_index('ix_meter_endpoint_assignments_meter_primary', 'meter_endpoint_assignments', ['meter_id', 'is_primary'], unique=False)
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = 'meter_connectivity_history'
            ) THEN
                DROP TABLE meter_connectivity_history;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_connectivity_history',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', 'unknown', name='connectivity_status'), nullable=False),
    sa.Column('session_reference', sa.String(length=128), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name=op.f('fk_meter_connectivity_history_meter_id_meters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_connectivity_history'))
    )
    op.create_index('ix_meter_connectivity_history_meter_recorded_at', 'meter_connectivity_history', ['meter_id', 'recorded_at'], unique=False)
    op.create_index('ix_meter_connectivity_history_meter_status', 'meter_connectivity_history', ['meter_id', 'status'], unique=False)
    op.drop_index('ix_meter_endpoint_assignments_meter_primary', table_name='meter_endpoint_assignments')
    op.drop_index('ix_meter_endpoint_assignments_meter_active', table_name='meter_endpoint_assignments')
    op.drop_index('ix_meter_endpoint_assignments_endpoint_active', table_name='meter_endpoint_assignments')
    op.drop_table('meter_endpoint_assignments')
    op.drop_index('ix_connectivity_session_history_status_started_at', table_name='connectivity_session_history')
    op.drop_index('ix_connectivity_session_history_recent_started_at', table_name='connectivity_session_history')
    op.drop_index('ix_connectivity_session_history_meter_started_at', table_name='connectivity_session_history')
    op.drop_index('ix_connectivity_session_history_endpoint_started_at', table_name='connectivity_session_history')
    op.drop_index('ix_connectivity_session_history_correlation_id', table_name='connectivity_session_history')
    op.drop_table('connectivity_session_history')
    op.drop_index('ix_protocol_association_profiles_protocol_family', table_name='protocol_association_profiles')
    op.drop_index('ix_protocol_association_profiles_is_active', table_name='protocol_association_profiles')
    op.drop_table('protocol_association_profiles')
    op.drop_index('ix_connectivity_credentials_is_active', table_name='connectivity_credentials')
    op.drop_table('connectivity_credentials')
    op.drop_index('ix_communication_endpoints_transport_type', table_name='communication_endpoints')
    op.drop_index('ix_communication_endpoints_is_active', table_name='communication_endpoints')
    op.drop_index('ix_communication_endpoints_endpoint_type', table_name='communication_endpoints')
    op.drop_table('communication_endpoints')
    # ### end Alembic commands ###
